#!/usr/bin/env python3
"""
ESPhub LabTest V1 UDP collector.

Purpose
-------
Receive bounded UDP test traffic generated by authorized ESPhub laboratory
nodes and produce a CSV log that can be correlated with Wireshark captures.

This tool does not generate traffic. It only listens locally on the three
default LabTest ports.

Default mapping:
    ESP32 DevKit V1 -> UDP/41001
    ESP32-C6        -> UDP/41002
    ESP32-S3        -> UDP/41003
"""

from __future__ import annotations

import argparse
import csv
import selectors
import socket
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import TextIO


DEFAULT_PORTS = (41001, 41002, 41003)
MAX_DATAGRAM = 2048
MAGIC = b"ESPHUB_LAB_V1|"


@dataclass
class PortStats:
    packets: int = 0
    bytes: int = 0
    first_monotonic: float | None = None
    last_monotonic: float | None = None
    last_seq_by_node: dict[str, int] = field(default_factory=dict)
    inferred_loss: int = 0

    def record(
        self,
        node: str,
        seq: int | None,
        size: int,
        now: float,
    ) -> None:
        if self.first_monotonic is None:
            self.first_monotonic = now

        self.last_monotonic = now
        self.packets += 1
        self.bytes += size

        if seq is None or not node:
            return

        previous = self.last_seq_by_node.get(node)

        if previous is not None and seq > previous + 1:
            self.inferred_loss += seq - previous - 1

        if previous is None or seq > previous:
            self.last_seq_by_node[node] = seq


def parse_header(payload: bytes) -> dict[str, str]:
    if not payload.startswith(MAGIC):
        return {}

    try:
        text = payload[: min(len(payload), 256)].decode(
            "ascii",
            errors="ignore",
        )
    except Exception:
        return {}

    fields: dict[str, str] = {}

    for item in text.split("|")[1:]:
        if "=" not in item:
            continue

        key, value = item.split("=", 1)
        key = key.strip()
        value = value.strip()

        if key:
            fields[key] = value

    return fields


def bind_socket(port: int) -> socket.socket:
    sock = socket.socket(
        socket.AF_INET,
        socket.SOCK_DGRAM,
    )

    sock.setsockopt(
        socket.SOL_SOCKET,
        socket.SO_REUSEADDR,
        1,
    )

    sock.bind(("0.0.0.0", port))
    sock.setblocking(False)
    return sock


def open_csv(path: Path) -> tuple[TextIO, csv.writer]:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    handle = path.open(
        "w",
        newline="",
        encoding="utf-8",
    )

    writer = csv.writer(handle)

    writer.writerow(
        (
            "unix_time",
            "local_time",
            "source_ip",
            "source_port",
            "listen_port",
            "size_bytes",
            "node",
            "level",
            "seq",
            "tx_ms",
        )
    )

    handle.flush()
    return handle, writer


def print_summary(
    stats: dict[int, PortStats],
    started: float,
) -> None:
    elapsed = max(
        time.monotonic() - started,
        0.001,
    )

    parts: list[str] = []

    for port in sorted(stats):
        current = stats[port]
        pps = current.packets / elapsed
        mbps = (
            current.bytes * 8
        ) / elapsed / 1_000_000

        parts.append(
            f"{port}: "
            f"{current.packets} pkt "
            f"{pps:.1f} pps "
            f"{mbps:.3f} Mb/s "
            f"loss~{current.inferred_loss}"
        )

    print(
        "[stats] " + " | ".join(parts),
        flush=True,
    )


def run(
    ports: tuple[int, ...],
    csv_path: Path,
) -> int:
    selector = selectors.DefaultSelector()
    sockets: list[socket.socket] = []

    for port in ports:
        sock = bind_socket(port)
        sockets.append(sock)
        selector.register(
            sock,
            selectors.EVENT_READ,
            data=port,
        )

    csv_file, writer = open_csv(csv_path)

    stats = {
        port: PortStats()
        for port in ports
    }

    started = time.monotonic()
    last_summary = started

    print(
        "ESPhub LabTest V1 collector",
        flush=True,
    )

    print(
        "Escutando UDP em: "
        + ", ".join(
            str(port)
            for port in ports
        ),
        flush=True,
    )

    print(
        f"CSV: {csv_path.resolve()}",
        flush=True,
    )

    print(
        "Wireshark filter: "
        + " || ".join(
            f"udp.port == {port}"
            for port in ports
        ),
        flush=True,
    )

    try:
        while True:
            events = selector.select(
                timeout=0.25
            )

            for key, _ in events:
                sock: socket.socket = key.fileobj
                listen_port: int = key.data

                while True:
                    try:
                        payload, source = sock.recvfrom(
                            MAX_DATAGRAM
                        )
                    except BlockingIOError:
                        break

                    now_monotonic = time.monotonic()
                    now_wall = time.time()
                    fields = parse_header(payload)

                    node = fields.get(
                        "node",
                        "",
                    )

                    seq_text = fields.get(
                        "seq",
                        "",
                    )

                    seq = (
                        int(seq_text)
                        if seq_text.isdigit()
                        else None
                    )

                    stats[listen_port].record(
                        node=node,
                        seq=seq,
                        size=len(payload),
                        now=now_monotonic,
                    )

                    writer.writerow(
                        (
                            f"{now_wall:.6f}",
                            time.strftime(
                                "%Y-%m-%d %H:%M:%S",
                                time.localtime(
                                    now_wall
                                ),
                            ),
                            source[0],
                            source[1],
                            listen_port,
                            len(payload),
                            node,
                            fields.get(
                                "level",
                                "",
                            ),
                            seq_text,
                            fields.get(
                                "tx_ms",
                                "",
                            ),
                        )
                    )

            now = time.monotonic()

            if now - last_summary >= 1.0:
                csv_file.flush()
                print_summary(
                    stats,
                    started,
                )
                last_summary = now

    except KeyboardInterrupt:
        print(
            "\nEncerrando coletor...",
            flush=True,
        )

    finally:
        csv_file.flush()
        csv_file.close()

        for sock in sockets:
            try:
                selector.unregister(sock)
            except Exception:
                pass

            sock.close()

        selector.close()

    print_summary(
        stats,
        started,
    )

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Coletor UDP do ESPhub LabTest V1. "
            "Escuta apenas no computador local."
        )
    )

    parser.add_argument(
        "--ports",
        nargs="+",
        type=int,
        default=list(DEFAULT_PORTS),
        help=(
            "Portas UDP a escutar. "
            "Padrão: 41001 41002 41003"
        ),
    )

    parser.add_argument(
        "--csv",
        type=Path,
        default=Path(
            "esphub_lab_capture.csv"
        ),
        help=(
            "Arquivo CSV de saída."
        ),
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    ports = tuple(
        dict.fromkeys(
            args.ports
        )
    )

    if not ports:
        print(
            "Nenhuma porta informada.",
            file=sys.stderr,
        )
        return 2

    for port in ports:
        if not 1024 <= port <= 65535:
            print(
                f"Porta inválida: {port}. "
                "Use 1024..65535.",
                file=sys.stderr,
            )
            return 2

    try:
        return run(
            ports=ports,
            csv_path=args.csv,
        )
    except OSError as error:
        print(
            f"Erro de socket: {error}",
            file=sys.stderr,
        )
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
